set_property SRC_FILE_INFO {cfile:C:/Users/zayam/Downloads/Basys-3-Keyboard-2018.2-3/vivado_proj/Basys-3-Keyboard.srcs/constrs_1/imports/constraints/Basys3_Master.xdc rfile:../../../../../Downloads/Basys-3-Keyboard-2018.2-3/vivado_proj/Basys-3-Keyboard.srcs/constrs_1/imports/constraints/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports tx]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports PS2Clk]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports PS2Data]
